### ISSUE TITLE
Sitecore 8.1 - ICorePipeline has moved to Sitecore.Abstractions

### ISSUE THREAD

**Issue by jasonbert** [ehabelgindy/sitecore-solr-spatial#1]
Just as an FYI, I had to add the Sitecore.Abstractions binary as a reference in the Sitecore.ContentSearch.Spatial.Solr project. It appears the ICorePipeline has moved to this binary.

**Comment by ehabelgindy** [comment]
Good shout!
What Sitecore version are you using?

**Comment by jasonbert** [comment]
8.1 rev. 151003 - Initial Release

**Comment by ehabelgindy** [comment]
Will update the code and release an 8.1 compatible package in the market place.
Thanks for raising this issue!

**Comment by jasonbert** [comment]
No problem - glad to help :)

**Comment by ehabelgindy** [comment]
Code has been updated

**Comment by tpkphani** [comment]
Hi,
I am using Solr search package to update Sitecore  8.1 rev. 151003 - Initial Release using SIM. However once I try to open the page I am getting the error "Method not found: 'System.String Sitecore.ContentSearch.Abstractions.ISettings.GetSetting(System.String, System.String)'. " . 
Am I missing something?

**Comment by ehabelgindy** [comment]
@tpkphani have you installed the 8.1 compatible package?

**Comment by tpkphani** [comment]
@ehabelgindy Sorry my bad. I referred wrong package.
I have one more question. The dll copied Castle.Windsor and Castle.Core are of old versions 3.1. In my existing project we are using 3.3 (for glass mapper). So I could not resolve it. Any idea how we can resolve this?
